// test action
export const TEST_ACTION = 'TEST_ACTION';
export const SECOND_TEST_ACTION = 'SECOND_TEST_ACTION';

// Clients
export const GET_SCHOOL = 'GET_SCHOOL';
export const GET_SCHOOLS = 'GET_SCHOOLS';
export const SET_SCHOOL = 'SET_SCHOOL';
export const PUT_SCHOOL = 'PUT_SCHOOL';
export const SEARCH_SCHOOLS = 'SEARCH_SCHOOLS';
export const POST_SCHOOL= 'POST_SCHOOL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';

// Reviews
export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEWS = 'GET_REVIEWS';
export const SET_REVIEW = 'SET_REVIEW';
export const PUT_REVIEW = 'PUT_REVIEW';
export const SEARCH_REVIEWS = 'SEARCH_REVIEWS';
export const POST_REVIEW= 'POST_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';

// Programs
export const GET_PROGRAM = 'GET_PROGRAM';
export const GET_PROGRAMS = 'GET_PROGRAMS';
export const SET_PROGRAM = 'SET_PROGRAM';
export const PUT_PROGRAM = 'PUT_PROGRAM';
export const SEARCH_PROGRAMS = 'SEARCH_PROGRAMS';
export const POST_PROGRAM= 'POST_PROGRAM';
export const DELETE_PROGRAM = 'DELETE_PROGRAM';


export const UPLOAD_CSV_SUCCESS = 'UPLOAD_CSV_SUCCESS';
export const UPLOAD_CSV_ERROR = 'UPLOAD_CSV_ERROR';
export const SHOW_IMPORT_CSV = 'SHOW_IMPORT_CSV';
export const HIDE_IMPORT_CSV = 'HIDE_IMPORT_CSV';

export const SET_DETAIL_VIEW = 'SET_DETAIL_VIEW';
export const SET_REVIEW_DETAIL_VIEW = 'SET_REVIEW_DETAIL_VIEW';

// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const USERNAME_CHANGE = 'USERNAME_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const RESET_FORM = 'RESET_FORM';

// Integrations
export const GET_INTEGRATIONS = 'GET_INTEGRATIONS';
export const GET_CLIENT_INTEGRATIONS = 'GET_CLIENT_INTEGRATIONS';
export const POST_INTEGRATIONS = 'POST_INTEGRATIONS';
export const PUT_INTEGRATIONS = 'PUT_INTEGRATIONS';

// Managers
export const GET_ACCOUNT_MANAGERS = 'GET_ACCOUNT_MANAGERS';
export const DELETE_ACCOUNT_MANAGER = 'DELETE_ACCOUNT_MANAGERS';
export const PUT_ACCOUNT_MANAGER = 'PUT_ACCOUNT_MANAGERS';
export const POST_ACCOUNT_MANAGER = 'POST_ACCOUNT_MANAGERS';
export const SHOW_NEW_MANAGER_VIEW = 'SHOW_NEW_MANAGER_VIEW';
export const HIDE_NEW_MANAGER_VIEW = 'HIDE_NEW_MANAGER_VIEW';

// Specialists
export const GET_SPECIALISTS = 'GET_SPECIALISTS';
export const POST_SPECIALIST = 'POST_SPECIALIST';
export const PUT_SPECIALIST = 'PUT_SPECIALIST';
export const DELETE_SPECIALIST = 'DELETE_SPECIALIST';
export const SHOW_NEW_SPECIALIST_VIEW = 'SHOW_NEW_SPECIALIST_VIEW';
export const HIDE_NEW_SPECIALIST_VIEW = 'HIDE_NEW_SPECIALIST_VIEW';

// Agency
export const GET_AGENCIES = 'GET_AGENCIES';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

// Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const CONFIRMED = 'CONFIRMED';
export const NO_MODAL = 'NO_MODAL';

// Navbar
export const HIDE_NEW_MANAGER_BUTTON = 'HIDE_NEW_MANAGER_BUTTON';
export const SHOW_NEW_MANAGER_BUTTON = 'SHOW_NEW_MANAGER_BUTTON';
export const HIDE_NEW_SPECIALIST_BUTTON = 'HIDE_NEW_SPECIALIST_BUTTON';
export const SHOW_NEW_SPECIALIST_BUTTON = 'SHOW_NEW_SPECIALIST_BUTTON';
export const HIDE_NEW_CLIENT_BUTTON = 'HIDE_NEW_CLIENT_BUTTON';
export const SHOW_NEW_CLIENT_BUTTON = 'SHOW_NEW_CLIENT_BUTTON';
export const HIDE_NEW_REVIEW_BUTTON = 'HIDE_NEW_REVIEW_BUTTON';
export const SHOW_NEW_REVIEW_BUTTON = 'SHOW_NEW_REVIEW_BUTTON';
export const HIDE_NEW_PROGRAM_BUTTON = 'HIDE_NEW_PROGRAM_BUTTON';
export const SHOW_NEW_PROGRAM_BUTTON = 'SHOW_NEW_PROGRAM_BUTTON';
